global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: "coordinator"
    static_configs:
      - targets: ["coordinator:8084"]
    metrics_path: "/metrics"

  - job_name: "bid-monitoring-service"
    static_configs:
      - targets: ["bid-monitoring-service:8088"]
    metrics_path: "/metrics"

  - job_name: "bids-api"
    static_configs:
      - targets: ["bids-api:8087"]
    metrics_path: "/metrics"

  - job_name: "contract-listener-service"
    static_configs:
      - targets: ["contract-listener:8080"]
    metrics_path: "/metrics"
