global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "bids-api"
    static_configs:
      - targets: ["bids-api.railway.internal:8087"]
    metrics_path: "/metrics"
